export const accounts = [
  {
    id: 1,
    rank: 1,
    company: 'Baker Tilly Regional',
    fitScore: 94,
    intentSignals: 5,
    strength: 'Hot',
    overview: {
      size: '120 employees across 3 offices',
      industry: 'Regional Accounting & Advisory',
      location: 'Milwaukee, WI (HQ) + Chicago, IL + Madison, WI',
      techStack: 'QuickBooks Enterprise, Karbon (workflow), Bill.com, Slack',
      revenue: '$18M ARR',
    },
    signals: [
      { type: 'Website Visit', detail: 'Visited pricing page 3x in 48 hours', time: '2 hours ago', icon: 'globe' },
      { type: 'Email Click', detail: 'Opened "Practice Management ROI" case study', time: '6 hours ago', icon: 'mail' },
      { type: 'Job Posting', detail: 'Posted "Practice Operations Manager" on LinkedIn', time: '1 day ago', icon: 'briefcase' },
      { type: 'LinkedIn Activity', detail: 'Managing Partner liked Financial Cents product update post', time: '1 day ago', icon: 'linkedin' },
      { type: 'Website Visit', detail: 'Viewed integrations page (QuickBooks section)', time: '2 days ago', icon: 'globe' },
    ],
    conversationStarters: [
      'Reference their new Practice Operations Manager role — signals they\'re investing in operational efficiency.',
      'Ask about their experience managing workflows across 3 offices with Karbon — Financial Cents centralizes multi-office visibility.',
      'Mention the ROI case study they opened — offer to walk through the numbers specific to a 120-person firm.',
    ],
    whyNow: 'Baker Tilly Regional is actively hiring for practice operations and consuming pricing/ROI content. Their multi-office setup with Karbon suggests workflow fragmentation. The managing partner is personally engaging with Financial Cents content — executive attention plus hiring signals indicate budget cycle timing.',
    callScript: {
      opening: 'Hi [Name], this is [Your Name] with Financial Cents. I noticed Baker Tilly Regional recently posted for a Practice Operations Manager — sounds like you\'re scaling your ops infrastructure. Do you have 30 seconds?',
      discoveryQuestions: [
        'How are you currently managing workflow visibility across your Milwaukee, Chicago, and Madison offices — is Karbon giving you the cross-office reporting you need?',
        'With 120 people and growing, what\'s the biggest bottleneck in your practice management today — capacity planning, client communication, or deadline tracking?',
        'When you think about what that new Practice Ops Manager will need on day one, what tools or dashboards are missing?',
      ],
      valueHook: 'We\'ve helped regional firms your size cut workflow setup time by 40% and give partners real-time visibility across every office — without replacing your existing QuickBooks or billing stack. The firms that switch from Karbon to Financial Cents for practice management typically see ROI in the first quarter.',
      nextStep: 'I\'d love to show you a 15-minute demo tailored to multi-office firms — I can have it ready for early next week. Would Tuesday or Wednesday work better for you and your managing partner?',
    },
  },
  {
    id: 2,
    rank: 2,
    company: 'Schechter Reed CPAs',
    fitScore: 89,
    intentSignals: 4,
    strength: 'Hot',
    overview: {
      size: '45 employees, single office',
      industry: 'Tax & Advisory CPA Firm',
      location: 'Austin, TX',
      techStack: 'Xero, Jetpack Workflow, Gusto, Microsoft Teams',
      revenue: '$6.2M ARR',
    },
    signals: [
      { type: 'Email Click', detail: 'Opened "Tax Season Workflow" email + clicked CTA', time: '4 hours ago', icon: 'mail' },
      { type: 'Website Visit', detail: 'Visited competitor comparison page (Financial Cents vs Jetpack)', time: '8 hours ago', icon: 'globe' },
      { type: 'LinkedIn Activity', detail: 'Firm admin commented on post about practice management pain points', time: '1 day ago', icon: 'linkedin' },
      { type: 'Website Visit', detail: 'Downloaded "CPA Firm Efficiency Guide" PDF', time: '3 days ago', icon: 'globe' },
    ],
    conversationStarters: [
      'Reference the competitor comparison page — they\'re actively evaluating switching from Jetpack Workflow.',
      'Ask about their tax season experience — they engaged with tax workflow content right after busy season.',
      'Mention their firm admin\'s LinkedIn comment about practice management challenges — validate the pain.',
    ],
    whyNow: 'Schechter Reed is in active evaluation mode — comparing Financial Cents to Jetpack Workflow directly. Post-tax season is the #1 window when CPA firms invest in better tools. Their engagement pattern (guide download > comparison > email click) shows classic buying journey acceleration.',
    callScript: {
      opening: 'Hi [Name], this is [Your Name] with Financial Cents. I saw your team has been researching practice management solutions — post-tax season is when most firms we work with decide to fix what broke during busy season. Quick question for you.',
      discoveryQuestions: [
        'Now that tax season is behind you, what was the biggest workflow bottleneck your team hit this year — was it deadline tracking, client follow-up, or capacity?',
        'I noticed you\'re currently on Jetpack Workflow — what\'s working well and what\'s falling short for a 45-person firm like yours?',
        'How much time does your team spend each week on status updates and manually tracking where engagements stand?',
      ],
      valueHook: 'CPA firms your size that switch from Jetpack to Financial Cents typically save 6-8 hours per week on workflow admin alone. Our platform was purpose-built for accounting firms — automated client requests, real-time capacity dashboards, and Xero integration that actually works. Most firms are fully migrated in under 2 weeks.',
      nextStep: 'I can set up a quick comparison demo — Jetpack side-by-side with Financial Cents using your actual workflow. Takes 20 minutes. Would Thursday afternoon work?',
    },
  },
  {
    id: 3,
    rank: 3,
    company: 'Pinnacle Advisory Group',
    fitScore: 82,
    intentSignals: 3,
    strength: 'Warm',
    overview: {
      size: '28 employees, single office',
      industry: 'Wealth Advisory & Tax Planning',
      location: 'Denver, CO',
      techStack: 'QuickBooks Online, Canopy, HubSpot CRM, Zoom',
      revenue: '$3.8M ARR',
    },
    signals: [
      { type: 'Website Visit', detail: 'Visited features page and watched product demo video', time: '1 day ago', icon: 'globe' },
      { type: 'Job Posting', detail: 'Hiring "Client Success Coordinator" on Indeed', time: '2 days ago', icon: 'briefcase' },
      { type: 'Email Click', detail: 'Opened monthly newsletter, clicked "Client Portal" feature link', time: '4 days ago', icon: 'mail' },
    ],
    conversationStarters: [
      'Reference the Client Success Coordinator hire — they\'re investing in client experience, Financial Cents\' client portal elevates that.',
      'Ask about their experience with Canopy for practice management — many advisory firms outgrow it.',
      'Mention the client portal feature they clicked on — it\'s a top differentiator for advisory firms.',
    ],
    whyNow: 'Pinnacle is hiring for client success and engaging with client portal content — signals a shift toward improving client-facing operations. Advisory firms with 28+ employees typically hit Canopy\'s limitations around reporting and workflow customization. The demo video watch indicates serious interest beyond casual browsing.',
    callScript: {
      opening: 'Hi [Name], this is [Your Name] with Financial Cents. I saw Pinnacle Advisory is bringing on a Client Success Coordinator — congratulations on the growth. I work with advisory firms that are scaling their client experience and had a quick thought for you.',
      discoveryQuestions: [
        'As you build out the client success function, what does the client communication workflow look like today — how are requests and documents flowing between your team and clients?',
        'How is Canopy handling your practice management needs as you\'ve grown to 28 people — are you seeing any limitations?',
        'What would the ideal client portal experience look like for your wealth advisory clients?',
      ],
      valueHook: 'Our client portal is purpose-built for firms like yours — clients can upload documents, track engagement progress, and communicate with your team in one branded experience. Advisory firms using Financial Cents see 35% faster document turnaround and significantly fewer "where\'s my return" emails. It\'s the kind of tool that makes your new Client Success Coordinator instantly effective.',
      nextStep: 'I\'d love to show you our client portal in action — it takes about 15 minutes and I can tailor it to wealth advisory workflows. Does early next week work for a quick call?',
    },
  },
  {
    id: 4,
    rank: 4,
    company: 'Greenline Bookkeeping Co.',
    fitScore: 78,
    intentSignals: 2,
    strength: 'Warm',
    overview: {
      size: '12 employees, fully remote',
      industry: 'Virtual Bookkeeping Services',
      location: 'Charlotte, NC (remote-first)',
      techStack: 'QuickBooks Online, Liscio, Asana, Slack',
      revenue: '$1.4M ARR',
    },
    signals: [
      { type: 'LinkedIn Activity', detail: 'Founder followed Financial Cents company page', time: '2 days ago', icon: 'linkedin' },
      { type: 'Website Visit', detail: 'Visited "For Bookkeepers" landing page', time: '5 days ago', icon: 'globe' },
    ],
    conversationStarters: [
      'Reference being a remote-first bookkeeping firm — Financial Cents was built for distributed teams.',
      'Ask about their experience juggling Asana + Liscio for practice management — Financial Cents replaces both.',
      'Mention the founder\'s LinkedIn follow — personalize around their growth trajectory.',
    ],
    whyNow: 'Greenline\'s founder is personally engaging with Financial Cents content, indicating top-down interest. Remote bookkeeping firms using Asana + Liscio together experience tool fragmentation that Financial Cents solves natively. At 12 employees, they\'re at the inflection point where manual processes break and dedicated practice management becomes essential.',
    callScript: {
      opening: 'Hi [Name], this is [Your Name] with Financial Cents. I noticed you recently checked out our bookkeeping-specific features — as a remote-first firm, you\'re exactly the type of team we built this for. Do you have a quick minute?',
      discoveryQuestions: [
        'Running a 12-person remote bookkeeping team — how are you managing work assignments and deadlines across your distributed team today?',
        'I see you\'re using Asana for project management and Liscio for client communication — how well are those two working together?',
        'What\'s your biggest operational challenge right now — is it capacity visibility, client communication, or keeping everyone on the same page remotely?',
      ],
      valueHook: 'Remote bookkeeping firms tell us the #1 problem is visibility — knowing who has capacity, what\'s overdue, and where client work stands without constant check-ins. Financial Cents replaces the Asana + Liscio combo with one platform built specifically for bookkeeping workflows. Firms your size typically get fully set up in a week and see immediate time savings.',
      nextStep: 'I can do a quick 15-minute walkthrough focused on remote bookkeeping teams — I\'ll show you exactly how it replaces your Asana and Liscio setup. Would later this week work?',
    },
  },
];

export const signalFeed = [
  { id: 1, account: 'Baker Tilly Regional', action: 'Visited pricing page (3rd time this week)', time: '2 hours ago', type: 'website', strength: 'hot' },
  { id: 2, account: 'Schechter Reed CPAs', action: 'Opened "Tax Season Workflow" email + clicked CTA', time: '4 hours ago', type: 'email', strength: 'hot' },
  { id: 3, account: 'Baker Tilly Regional', action: 'Opened ROI case study email', time: '6 hours ago', type: 'email', strength: 'hot' },
  { id: 4, account: 'Schechter Reed CPAs', action: 'Viewed competitor comparison page', time: '8 hours ago', type: 'website', strength: 'hot' },
  { id: 5, account: 'Pinnacle Advisory Group', action: 'Watched product demo video (full)', time: '1 day ago', type: 'website', strength: 'warm' },
  { id: 6, account: 'Baker Tilly Regional', action: 'Managing Partner liked product update post', time: '1 day ago', type: 'linkedin', strength: 'warm' },
  { id: 7, account: 'Schechter Reed CPAs', action: 'Firm admin commented on practice mgmt post', time: '1 day ago', type: 'linkedin', strength: 'warm' },
  { id: 8, account: 'Pinnacle Advisory Group', action: 'Hiring "Client Success Coordinator"', time: '2 days ago', type: 'job', strength: 'warm' },
  { id: 9, account: 'Baker Tilly Regional', action: 'Viewed integrations page (QuickBooks)', time: '2 days ago', type: 'website', strength: 'warm' },
  { id: 10, account: 'Greenline Bookkeeping Co.', action: 'Founder followed company page on LinkedIn', time: '2 days ago', type: 'linkedin', strength: 'warm' },
  { id: 11, account: 'Schechter Reed CPAs', action: 'Downloaded CPA Firm Efficiency Guide', time: '3 days ago', type: 'website', strength: 'warm' },
  { id: 12, account: 'Pinnacle Advisory Group', action: 'Clicked "Client Portal" link in newsletter', time: '4 days ago', type: 'email', strength: 'warm' },
  { id: 13, account: 'Greenline Bookkeeping Co.', action: 'Visited "For Bookkeepers" landing page', time: '5 days ago', type: 'website', strength: 'warm' },
];

export const summaryStats = {
  accountsInQueue: 4,
  hotSignalsToday: 7,
  avgFitScore: 86,
  callsCompleted: '0 / 4',
};
