export const accounts = [
  {
    id: 1,
    priority: 1,
    company: 'Whitfield & Associates CPAs',
    fitScore: 94,
    intentScore: 91,
    timingScore: 96,
    signalCount: 5,
    strength: 'Hot',
    status: 'New',
    lastActivity: '2 hours ago',
    website: 'whitfieldcpas.com',
    overview: {
      size: '45 employees',
      industry: 'Accounting & Tax Services',
      location: 'Atlanta, GA',
      revenue: '$6.8M ARR',
      currentTools: 'QuickBooks + Spreadsheets',
      founded: '2011',
      specialties: 'Tax preparation, bookkeeping, business advisory',
    },
    contacts: [
      { name: 'David Whitfield', title: 'Managing Partner', email: 'd.whitfield@whitfieldcpas.com', phone: '(404) 555-0142', isPrimary: true },
      { name: 'Sarah Chen', title: 'Practice Manager', email: 's.chen@whitfieldcpas.com', phone: '(404) 555-0187', isPrimary: false },
      { name: 'Marcus Johnson', title: 'Director of Operations', email: 'm.johnson@whitfieldcpas.com', phone: '(404) 555-0203', isPrimary: false },
    ],
    signals: [
      { type: 'Website Visit', detail: 'Visited pricing page 3x this week — compared annual vs monthly plans', time: '2 hours ago', icon: 'globe', strength: 'hot' },
      { type: 'Email Engagement', detail: 'Opened comparison email "Financial Cents vs Spreadsheets" — clicked CTA twice', time: '5 hours ago', icon: 'mail', strength: 'hot' },
      { type: 'Job Posting', detail: 'Posted "Practice Manager" role on LinkedIn — requires PM software experience', time: '1 day ago', icon: 'briefcase', strength: 'hot' },
      { type: 'Website Visit', detail: 'Viewed case study: "How a 50-person firm eliminated spreadsheet chaos"', time: '2 days ago', icon: 'globe', strength: 'warm' },
      { type: 'LinkedIn Activity', detail: 'David Whitfield liked Financial Cents LinkedIn post about workflow automation', time: '3 days ago', icon: 'linkedin', strength: 'warm' },
    ],
    conversationStarters: [
      "They just posted for a Practice Manager — they're building infrastructure to scale. Ask what tools the new hire will need on day one.",
      "They visited pricing 3x this week and compared plans. They're in buying mode. Reference the annual plan savings.",
      "They're still on spreadsheets at 45 people — that's painful. Ask how many hours per week go into manual tracking.",
    ],
    whyNow: "Whitfield & Associates is at a critical inflection point. At 45 employees managing workflows with spreadsheets, they're experiencing the pain that drives firms to adopt practice management software. The Practice Manager job posting signals executive commitment to operational improvement, and 3 pricing page visits in one week indicates budget conversations are happening NOW.",
    callScript: {
      opening: "Hi David, this is [Your Name] with Financial Cents. I noticed Whitfield & Associates just posted for a Practice Manager — sounds like you're scaling your operations. I work with a lot of 40-50 person firms making that exact transition. Do you have 30 seconds?",
      discoveryQuestions: [
        "You're at 45 people managing workflows with QuickBooks and spreadsheets — what's the biggest pain point that's driving the Practice Manager hire?",
        "How many hours per week would you estimate your team spends on manual status updates, deadline tracking, and figuring out who has capacity?",
        "When you picture what great looks like for your new Practice Manager on day one — what tools and dashboards would they need to be effective immediately?",
      ],
      valueHook: "We built Financial Cents specifically for firms like yours that have outgrown spreadsheets but don't want some bloated enterprise system. Firms your size typically save 8-10 hours per week on workflow admin, and your new Practice Manager would have real-time dashboards from day one — no manual tracking needed.",
      objectionHandler: "If they say 'We're evaluating options': That's smart — most firms your size look at 2-3 tools. What I can tell you is we're purpose-built for accounting firms, not a generic PM tool. Happy to do a quick side-by-side if you're comparing.",
      suggestedCTA: "Book a 15-minute demo tailored to firms transitioning from spreadsheets — show the specific workflow migration path.",
    },
    recommendedActions: [
      { type: 'call', label: 'Call David Whitfield', subtitle: 'Managing Partner — (404) 555-0142', priority: 'high' },
      { type: 'email', label: 'Send personalized email', subtitle: 'Reference pricing page visits + PM hire', priority: 'high' },
      { type: 'deal', label: 'Create deal in pipeline', subtitle: 'Est. value: $14,400/yr (45 seats)', priority: 'medium' },
    ],
  },
  {
    id: 2,
    priority: 2,
    company: 'Summit Ledger Group',
    fitScore: 91,
    intentScore: 88,
    timingScore: 85,
    signalCount: 4,
    strength: 'Hot',
    status: 'New',
    lastActivity: '4 hours ago',
    website: 'summitledger.com',
    overview: {
      size: '28 employees',
      industry: 'Bookkeeping & Accounting Services',
      location: 'Denver, CO',
      revenue: '$3.2M ARR',
      currentTools: 'TaxDome (competitor)',
      founded: '2015',
      specialties: 'Bookkeeping, payroll services, tax filing',
    },
    contacts: [
      { name: 'Rachel Morrison', title: 'CEO / Founder', email: 'rachel@summitledger.com', phone: '(720) 555-0318', isPrimary: true },
      { name: 'James Park', title: 'Operations Lead', email: 'james@summitledger.com', phone: '(720) 555-0322', isPrimary: false },
      { name: 'Nina Alvarez', title: 'Client Services Manager', email: 'nina@summitledger.com', phone: '(720) 555-0341', isPrimary: false },
    ],
    signals: [
      { type: 'Website Visit', detail: 'Visited TaxDome migration guide page — spent 4 minutes reading', time: '4 hours ago', icon: 'globe', strength: 'hot' },
      { type: 'LinkedIn Activity', detail: 'Rachel Morrison (CEO) liked Financial Cents post about switching PM tools', time: '8 hours ago', icon: 'linkedin', strength: 'hot' },
      { type: 'Website Visit', detail: 'Viewed "Switch from TaxDome" comparison page', time: '1 day ago', icon: 'globe', strength: 'hot' },
      { type: 'Email Engagement', detail: 'Opened drip email: "Why bookkeeping firms are leaving TaxDome"', time: '2 days ago', icon: 'mail', strength: 'warm' },
    ],
    conversationStarters: [
      "They're actively researching how to migrate from TaxDome. Ask what's frustrating them about their current setup.",
      "CEO is personally engaging with your content — this is top-down interest. Reference Rachel by name.",
      "They read the migration guide for 4 minutes — they're serious. Offer a migration walkthrough.",
    ],
    whyNow: "Summit Ledger is showing classic competitor-displacement signals. The CEO is personally engaging with content about switching from TaxDome, and they've visited the migration guide — that's not casual browsing. TaxDome's recent pricing changes have pushed many bookkeeping firms to evaluate alternatives. Strike while the iron is hot.",
    callScript: {
      opening: "Hi Rachel, this is [Your Name] from Financial Cents. I noticed your team has been researching practice management alternatives — a lot of bookkeeping firms we work with made a similar move from TaxDome recently. Quick question for you.",
      discoveryQuestions: [
        "What initially drew you to TaxDome, and what's changed? Most firms we talk to cite workflow limitations or the recent pricing changes — is that resonating?",
        "With 28 people, how is TaxDome handling your workflow management and team capacity planning? Those are usually the first things that break at your size.",
        "If you could wave a magic wand and fix one thing about your current practice management setup, what would it be?",
      ],
      valueHook: "We've migrated over 200 firms from TaxDome in the last year. The most common feedback is that Financial Cents gives them the workflow depth TaxDome lacks — real capacity planning, automated client requests, and reporting that actually shows firm-wide performance. Most migrations take under 10 days with zero data loss.",
      objectionHandler: "If they say 'We just renewed TaxDome': Totally understand. Most firms that switch planned it a quarter in advance. Happy to do a comparison now so you're ready when renewal comes up — no pressure.",
      suggestedCTA: "Offer a free migration assessment — show exactly what the TaxDome-to-Financial Cents transition looks like for a 28-person firm.",
    },
    recommendedActions: [
      { type: 'call', label: 'Call Rachel Morrison', subtitle: 'CEO / Founder — (720) 555-0318', priority: 'high' },
      { type: 'email', label: 'Send migration case study', subtitle: 'Include TaxDome-specific comparison data', priority: 'high' },
      { type: 'deal', label: 'Create deal in pipeline', subtitle: 'Est. value: $8,400/yr (28 seats)', priority: 'medium' },
    ],
  },
  {
    id: 3,
    priority: 3,
    company: 'Brookhaven Tax & Advisory',
    fitScore: 88,
    intentScore: 92,
    timingScore: 80,
    signalCount: 4,
    strength: 'Warm',
    status: 'Engaged',
    lastActivity: '6 hours ago',
    website: 'brookhaventax.com',
    overview: {
      size: '62 employees across 2 offices',
      industry: 'Tax Advisory & Compliance',
      location: 'Chicago, IL',
      revenue: '$9.4M ARR',
      currentTools: 'Karbon (competitor)',
      founded: '2008',
      specialties: 'Tax planning, compliance, M&A advisory, estate planning',
    },
    contacts: [
      { name: 'Patricia Brennan', title: 'COO', email: 'p.brennan@brookhaventax.com', phone: '(312) 555-0456', isPrimary: true },
      { name: 'Tom Nakamura', title: 'IT Director', email: 't.nakamura@brookhaventax.com', phone: '(312) 555-0489', isPrimary: false },
      { name: 'Lisa Ferraro', title: 'Managing Partner', email: 'l.ferraro@brookhaventax.com', phone: '(312) 555-0501', isPrimary: false },
    ],
    signals: [
      { type: 'Email Reply', detail: 'Replied to outreach sequence asking for demo — "Can we see the Karbon comparison?"', time: '6 hours ago', icon: 'mail', strength: 'hot' },
      { type: 'Webinar', detail: 'Attended "Scaling Your Firm Beyond 50 Employees" webinar — stayed for full Q&A', time: '3 days ago', icon: 'globe', strength: 'hot' },
      { type: 'Website Visit', detail: 'Visited features page, spent 6 min on workflow automation section', time: '4 days ago', icon: 'globe', strength: 'warm' },
      { type: 'LinkedIn Activity', detail: 'Tom Nakamura connected with Financial Cents sales rep', time: '5 days ago', icon: 'linkedin', strength: 'warm' },
    ],
    conversationStarters: [
      "They literally asked for a Karbon comparison in their email reply. Lead with that — they're ready to evaluate.",
      "They attended the full webinar including Q&A — ask what questions resonated with their situation.",
      "At 62 employees across 2 offices with Karbon, ask about cross-office workflow visibility challenges.",
    ],
    whyNow: "Brookhaven is the warmest lead in the queue because they REPLIED asking for a demo. The COO attended a scaling webinar and stayed for Q&A — this signals executive sponsorship. Their IT Director connected with your sales rep on LinkedIn. Multiple stakeholders are engaged simultaneously, which is a buying committee forming.",
    callScript: {
      opening: "Hi Patricia, this is [Your Name] with Financial Cents. Thank you for your reply asking about the Karbon comparison — I actually put together a side-by-side specifically for 60+ person firms. Want me to walk you through the highlights?",
      discoveryQuestions: [
        "You mentioned wanting to see the Karbon comparison — what specifically about Karbon is prompting you to look at alternatives right now?",
        "Managing 62 people across two offices — how are you handling workflow visibility and capacity planning between locations today?",
        "I saw you attended our scaling webinar — what resonated most? Was it the multi-office workflow piece or the reporting capabilities?",
      ],
      valueHook: "Firms your size that switch from Karbon to Financial Cents typically see two big wins: first, real-time cross-office visibility without manual status updates, and second, reporting that actually shows partner-level insights — not just task completion. Our 60+ person firms average 30% faster engagement completion after switching.",
      objectionHandler: "If they say 'We need to involve more stakeholders': Absolutely — I saw Tom from your IT team already connected with us. Happy to set up a session for the full evaluation team. We also have a Karbon migration assessment that's really helpful for technical stakeholders.",
      suggestedCTA: "Schedule the Karbon comparison demo they requested — include both Patricia (COO) and Tom (IT Director) on the invite.",
    },
    recommendedActions: [
      { type: 'call', label: 'Call Patricia Brennan', subtitle: 'COO — (312) 555-0456', priority: 'high' },
      { type: 'email', label: 'Send Karbon comparison deck', subtitle: 'They specifically requested this', priority: 'high' },
      { type: 'deal', label: 'Create deal in pipeline', subtitle: 'Est. value: $18,600/yr (62 seats)', priority: 'medium' },
    ],
  },
  {
    id: 4,
    priority: 4,
    company: 'Coastal Accounting Partners',
    fitScore: 82,
    intentScore: 75,
    timingScore: 78,
    signalCount: 3,
    strength: 'Warm',
    status: 'New',
    lastActivity: '1 day ago',
    website: 'coastalaccounting.com',
    overview: {
      size: '18 employees',
      industry: 'Accounting & Business Advisory',
      location: 'San Diego, CA',
      revenue: '$2.1M ARR',
      currentTools: 'No current PM tool — using email + Google Sheets',
      founded: '2017',
      specialties: 'Small business accounting, advisory, tax services',
    },
    contacts: [
      { name: 'Mike Donovan', title: 'Founding Partner', email: 'mike@coastalaccounting.com', phone: '(619) 555-0227', isPrimary: true },
      { name: 'Jen Castellano', title: 'Office Manager', email: 'jen@coastalaccounting.com', phone: '(619) 555-0234', isPrimary: false },
    ],
    signals: [
      { type: 'Content Download', detail: 'Downloaded whitepaper: "The Practice Management Buyer\'s Guide for Growing Firms"', time: '1 day ago', icon: 'globe', strength: 'warm' },
      { type: 'Blog Engagement', detail: 'Read 3 blog posts on workflow automation in 2 days', time: '2 days ago', icon: 'globe', strength: 'warm' },
      { type: 'Website Visit', detail: 'Visited "For Small Firms" landing page and features overview', time: '3 days ago', icon: 'globe', strength: 'warm' },
    ],
    conversationStarters: [
      "They downloaded the buyer's guide — they're in research mode. Position yourself as a helpful advisor, not a seller.",
      "Reading 3 blog posts on workflow automation signals a specific pain point. Ask what triggered the research.",
      "At 18 people with no PM tool, they're probably drowning in email. Ask about their current workflow.",
    ],
    whyNow: "Coastal Accounting is in early-stage research but showing strong educational engagement. Downloading a buyer's guide and reading 3 automation blog posts in 2 days indicates active problem-solving. At 18 employees with no PM tool, they're at the exact size where manual processes become unsustainable. They need education-first outreach, not a hard sell.",
    callScript: {
      opening: "Hi Mike, this is [Your Name] with Financial Cents. I saw you downloaded our Practice Management Buyer's Guide — sounds like you're thinking about streamlining operations at Coastal Accounting. I help firms your size figure out what they actually need. Quick question for you.",
      discoveryQuestions: [
        "What prompted you to start researching practice management tools right now? Was there a specific pain point or breaking point?",
        "Without a dedicated PM tool, how is your team of 18 tracking deadlines, client work status, and who has capacity?",
        "When you read those blog posts about workflow automation — what clicked for you? What would automating look like for your firm?",
      ],
      valueHook: "Most 18-person firms we work with were in the exact same spot — email and Google Sheets technically work, until they don't. The firms that adopt Financial Cents at your stage typically avoid the growing pains that hit at 25-30 employees. You get workflow templates built for accounting firms, automated client reminders, and a dashboard that shows you firm performance at a glance — no spreadsheet required.",
      objectionHandler: "If they say 'We're not ready yet': Totally fair — that's actually why the buyer's guide is helpful. Most firms research for 2-3 months before deciding. Happy to be a resource along the way. Can I send you a case study of a firm that made the switch at exactly your size?",
      suggestedCTA: "Offer a no-pressure 'practice management assessment' — 15 minutes to map out what they'd need based on their firm size and workflows.",
    },
    recommendedActions: [
      { type: 'call', label: 'Call Mike Donovan', subtitle: 'Founding Partner — (619) 555-0227', priority: 'medium' },
      { type: 'email', label: 'Send case study email', subtitle: 'Similar-sized firm success story', priority: 'medium' },
      { type: 'deal', label: 'Create deal in pipeline', subtitle: 'Est. value: $5,400/yr (18 seats)', priority: 'low' },
    ],
  },
];

export const signalFeed = [
  { id: 1, accountId: 1, account: 'Whitfield & Associates CPAs', action: 'Visited pricing page — 3rd time this week, compared annual vs monthly', time: '2 hours ago', type: 'website', strength: 'hot' },
  { id: 2, accountId: 2, account: 'Summit Ledger Group', action: 'Viewed TaxDome migration guide — spent 4 minutes reading', time: '4 hours ago', type: 'website', strength: 'hot' },
  { id: 3, accountId: 1, account: 'Whitfield & Associates CPAs', action: 'Opened comparison email "Financial Cents vs Spreadsheets" — clicked CTA', time: '5 hours ago', type: 'email', strength: 'hot' },
  { id: 4, accountId: 3, account: 'Brookhaven Tax & Advisory', action: 'Replied to sequence: "Can we see the Karbon comparison?"', time: '6 hours ago', type: 'email', strength: 'hot' },
  { id: 5, accountId: 2, account: 'Summit Ledger Group', action: 'CEO liked Financial Cents post about switching PM tools', time: '8 hours ago', type: 'linkedin', strength: 'hot' },
  { id: 6, accountId: 1, account: 'Whitfield & Associates CPAs', action: 'Posted "Practice Manager" role on LinkedIn', time: '1 day ago', type: 'job', strength: 'hot' },
  { id: 7, accountId: 4, account: 'Coastal Accounting Partners', action: 'Downloaded "Practice Management Buyer\'s Guide" whitepaper', time: '1 day ago', type: 'website', strength: 'warm' },
  { id: 8, accountId: 2, account: 'Summit Ledger Group', action: 'Viewed "Switch from TaxDome" comparison page', time: '1 day ago', type: 'website', strength: 'warm' },
  { id: 9, accountId: 1, account: 'Whitfield & Associates CPAs', action: 'Viewed case study: "50-person firm eliminated spreadsheet chaos"', time: '2 days ago', type: 'website', strength: 'warm' },
  { id: 10, accountId: 2, account: 'Summit Ledger Group', action: 'Opened drip email: "Why bookkeeping firms are leaving TaxDome"', time: '2 days ago', type: 'email', strength: 'warm' },
  { id: 11, accountId: 4, account: 'Coastal Accounting Partners', action: 'Read 3 blog posts on workflow automation in 2 days', time: '2 days ago', type: 'website', strength: 'warm' },
  { id: 12, accountId: 3, account: 'Brookhaven Tax & Advisory', action: 'Attended "Scaling Beyond 50 Employees" webinar — full session + Q&A', time: '3 days ago', type: 'website', strength: 'warm' },
  { id: 13, accountId: 1, account: 'Whitfield & Associates CPAs', action: 'David Whitfield liked Financial Cents LinkedIn post', time: '3 days ago', type: 'linkedin', strength: 'warm' },
  { id: 14, accountId: 4, account: 'Coastal Accounting Partners', action: 'Visited "For Small Firms" landing page and features overview', time: '3 days ago', type: 'website', strength: 'warm' },
  { id: 15, accountId: 3, account: 'Brookhaven Tax & Advisory', action: 'Viewed features page — 6 min on workflow automation section', time: '4 days ago', type: 'website', strength: 'warm' },
  { id: 16, accountId: 3, account: 'Brookhaven Tax & Advisory', action: 'IT Director connected with Financial Cents sales rep on LinkedIn', time: '5 days ago', type: 'linkedin', strength: 'warm' },
];

export const performanceData = {
  callsMade: 12,
  callsTarget: 20,
  pipelineGenerated: '$47,200',
  pipelineTarget: '$60,000',
  signalToMeeting: '34%',
  meetingsBooked: 6,
  avgResponseTime: '2.4 hrs',
  topSignals: [
    { type: 'Pricing Page Visit', conversions: 42, total: 100 },
    { type: 'Competitor Research', conversions: 38, total: 100 },
    { type: 'Content Download', conversions: 28, total: 100 },
    { type: 'Email Reply', conversions: 67, total: 100 },
    { type: 'Job Posting', conversions: 31, total: 100 },
  ],
  weeklyTrend: [
    { day: 'Mon', calls: 4, meetings: 1 },
    { day: 'Tue', calls: 3, meetings: 2 },
    { day: 'Wed', calls: 5, meetings: 1 },
    { day: 'Thu', calls: 0, meetings: 0 },
    { day: 'Fri', calls: 0, meetings: 0 },
  ],
};

export const summaryStats = {
  todayQueue: 4,
  signalsDetected: 12,
  estimatedPipeline: '$47,200',
  queueCompletion: '0/4',
};
