/* ═══════════════════════════════════════════════════════════════
   MOCK DATA — Financial Cents SDR Action Queue
   All 18 daily actions + accounts + signals + performance
   ═══════════════════════════════════════════════════════════════ */

export const accounts = [
  {
    id: 'whitfield',
    company: 'Whitfield & Associates CPAs',
    size: '45 employees',
    location: 'Atlanta, GA',
    industry: 'Accounting & Tax Services',
    revenue: '$6.8M ARR',
    currentTools: 'QuickBooks + Spreadsheets',
    founded: '2011',
    specialties: 'Tax preparation, bookkeeping, business advisory',
    website: 'whitfieldcpas.com',
    aiScore: 94,
    fitScore: 94,
    intentScore: 91,
    timingScore: 96,
    dealValue: '$14,400/yr',
    seats: 45,
    whyPrioritized: 'Pricing page visited 3x this week + Practice Manager job posting signals executive commitment to ops improvement. At 45 employees on spreadsheets, they are at the exact inflection point where firms adopt PM software. Multiple hot signals in 72 hours.',
    contacts: [
      { name: 'David Whitfield', title: 'Managing Partner', email: 'd.whitfield@whitfieldcpas.com', phone: '(404) 555-0142', isPrimary: true },
      { name: 'Sarah Chen', title: 'Practice Manager', email: 's.chen@whitfieldcpas.com', phone: '(404) 555-0187' },
      { name: 'Marcus Johnson', title: 'Director of Operations', email: 'm.johnson@whitfieldcpas.com', phone: '(404) 555-0203' },
    ],
    signals: [
      { type: 'Website Visit', detail: 'Visited pricing page 3x this week — compared annual vs monthly plans', time: '2 hours ago', strength: 'hot' },
      { type: 'Email Engagement', detail: 'Opened comparison email "Financial Cents vs Spreadsheets" — clicked CTA twice', time: '5 hours ago', strength: 'hot' },
      { type: 'Job Posting', detail: 'Posted "Practice Manager" role on LinkedIn — requires PM software experience', time: '1 day ago', strength: 'hot' },
      { type: 'Website Visit', detail: 'Viewed case study: "How a 50-person firm eliminated spreadsheet chaos"', time: '2 days ago', strength: 'warm' },
      { type: 'LinkedIn Activity', detail: 'David Whitfield liked Financial Cents LinkedIn post about workflow automation', time: '3 days ago', strength: 'warm' },
    ],
    callScript: {
      opening: "Hi David, this is Sarah with Financial Cents. I noticed Whitfield & Associates just posted for a Practice Manager — sounds like you're scaling your operations. I work with a lot of 40-50 person firms making that exact transition. Do you have 30 seconds?",
      discoveryQuestions: [
        "You're at 45 people managing workflows with QuickBooks and spreadsheets — what's the biggest pain point driving the Practice Manager hire?",
        "How many hours per week would you estimate your team spends on manual status updates and deadline tracking?",
      ],
      objectionHandler: "If 'evaluating options': Most firms your size look at 2-3 tools. We're purpose-built for accounting firms, not a generic PM tool. Happy to do a quick side-by-side.",
      suggestedCTA: "Book a 15-minute demo tailored to firms transitioning from spreadsheets.",
    },
  },
  {
    id: 'summit',
    company: 'Summit Ledger Group',
    size: '28 employees',
    location: 'Denver, CO',
    industry: 'Bookkeeping & Accounting',
    revenue: '$3.2M ARR',
    currentTools: 'TaxDome (competitor)',
    founded: '2015',
    specialties: 'Bookkeeping, payroll services, tax filing',
    website: 'summitledger.com',
    aiScore: 88,
    fitScore: 91,
    intentScore: 88,
    timingScore: 85,
    dealValue: '$8,400/yr',
    seats: 28,
    whyPrioritized: 'CEO personally researching TaxDome alternatives. Migration guide viewed yesterday. Classic competitor-displacement signals — TaxDome pricing changes pushing firms to evaluate. Multiple content engagements in 48 hours.',
    contacts: [
      { name: 'Rachel Morrison', title: 'CEO / Founder', email: 'rachel@summitledger.com', phone: '(720) 555-0318', isPrimary: true },
      { name: 'James Park', title: 'Operations Lead', email: 'james@summitledger.com', phone: '(720) 555-0322' },
      { name: 'Nina Alvarez', title: 'Client Services Manager', email: 'nina@summitledger.com', phone: '(720) 555-0341' },
    ],
    signals: [
      { type: 'Website Visit', detail: 'Visited TaxDome migration guide page — spent 4 minutes reading', time: '4 hours ago', strength: 'hot' },
      { type: 'LinkedIn Activity', detail: 'Rachel Morrison (CEO) liked Financial Cents post about switching PM tools', time: '8 hours ago', strength: 'hot' },
      { type: 'Website Visit', detail: 'Viewed "Switch from TaxDome" comparison page', time: '1 day ago', strength: 'hot' },
      { type: 'Email Engagement', detail: 'Opened drip email: "Why bookkeeping firms are leaving TaxDome"', time: '2 days ago', strength: 'warm' },
    ],
    callScript: {
      opening: "Hi Rachel, this is Sarah from Financial Cents. I noticed your team has been researching practice management alternatives — a lot of bookkeeping firms we work with made a similar move from TaxDome recently. Quick question for you.",
      discoveryQuestions: [
        "What initially drew you to TaxDome, and what's changed? Most firms cite workflow limitations or the recent pricing changes.",
        "With 28 people, how is TaxDome handling your workflow management and team capacity planning?",
      ],
      objectionHandler: "If 'just renewed TaxDome': Most firms that switch planned it a quarter in advance. Happy to do a comparison now so you're ready at renewal.",
      suggestedCTA: "Offer a free migration assessment — show what the TaxDome-to-Financial Cents transition looks like for a 28-person firm.",
    },
  },
  {
    id: 'brookhaven',
    company: 'Brookhaven Tax & Advisory',
    size: '62 employees, 2 offices',
    location: 'Chicago, IL',
    industry: 'Tax Advisory & Compliance',
    revenue: '$9.4M ARR',
    currentTools: 'Karbon (competitor)',
    founded: '2008',
    specialties: 'Tax planning, compliance, M&A advisory, estate planning',
    website: 'brookhaventax.com',
    aiScore: 90,
    fitScore: 88,
    intentScore: 92,
    timingScore: 80,
    dealValue: '$18,600/yr',
    seats: 62,
    whyPrioritized: 'COO replied asking for Karbon comparison — warmest lead in queue. Attended scaling webinar with full Q&A. IT Director connected on LinkedIn. Multiple stakeholders engaged = buying committee forming.',
    contacts: [
      { name: 'Patricia Brennan', title: 'COO', email: 'p.brennan@brookhaventax.com', phone: '(312) 555-0456', isPrimary: true },
      { name: 'Tom Nakamura', title: 'IT Director', email: 't.nakamura@brookhaventax.com', phone: '(312) 555-0489' },
      { name: 'Lisa Ferraro', title: 'Managing Partner', email: 'l.ferraro@brookhaventax.com', phone: '(312) 555-0501' },
    ],
    signals: [
      { type: 'Email Reply', detail: 'Replied to outreach: "Can we see the Karbon comparison?"', time: '6 hours ago', strength: 'hot' },
      { type: 'Webinar', detail: 'Attended "Scaling Beyond 50 Employees" webinar — stayed for full Q&A', time: '3 days ago', strength: 'hot' },
      { type: 'Website Visit', detail: 'Viewed features page — 6 min on workflow automation section', time: '4 days ago', strength: 'warm' },
      { type: 'LinkedIn Activity', detail: 'Tom Nakamura connected with Financial Cents sales rep', time: '5 days ago', strength: 'warm' },
    ],
    callScript: {
      opening: "Hi Patricia, this is Sarah with Financial Cents. Thank you for your reply asking about the Karbon comparison — I put together a side-by-side specifically for 60+ person firms. Want me to walk you through the highlights?",
      discoveryQuestions: [
        "You mentioned wanting to see the Karbon comparison — what specifically is prompting you to look at alternatives?",
        "Managing 62 people across two offices — how are you handling workflow visibility between locations today?",
      ],
      objectionHandler: "If 'need more stakeholders': I saw Tom from IT already connected with us. Happy to set up a session for the full evaluation team.",
      suggestedCTA: "Schedule Karbon comparison demo — include Patricia (COO) and Tom (IT Director).",
    },
  },
  {
    id: 'coastal',
    company: 'Coastal Accounting Partners',
    size: '18 employees',
    location: 'San Diego, CA',
    industry: 'Accounting & Business Advisory',
    revenue: '$2.1M ARR',
    currentTools: 'Email + Google Sheets',
    founded: '2017',
    specialties: 'Small business accounting, advisory, tax services',
    website: 'coastalaccounting.com',
    aiScore: 78,
    fitScore: 82,
    intentScore: 75,
    timingScore: 78,
    dealValue: '$5,400/yr',
    seats: 18,
    whyPrioritized: 'Downloaded buyer\'s guide + read 3 automation blog posts in 2 days. Early research phase but strong educational engagement. At 18 employees with no PM tool, they are at the size where manual processes become unsustainable.',
    contacts: [
      { name: 'Mike Donovan', title: 'Founding Partner', email: 'mike@coastalaccounting.com', phone: '(619) 555-0227', isPrimary: true },
      { name: 'Jen Castellano', title: 'Office Manager', email: 'jen@coastalaccounting.com', phone: '(619) 555-0234' },
    ],
    signals: [
      { type: 'Content Download', detail: 'Downloaded "Practice Management Buyer\'s Guide for Growing Firms"', time: '1 day ago', strength: 'warm' },
      { type: 'Blog Engagement', detail: 'Read 3 blog posts on workflow automation in 2 days', time: '2 days ago', strength: 'warm' },
      { type: 'Website Visit', detail: 'Visited "For Small Firms" landing page and features overview', time: '3 days ago', strength: 'warm' },
    ],
    callScript: {
      opening: "Hi Mike, this is Sarah with Financial Cents. I saw you downloaded our Practice Management Buyer's Guide — sounds like you're thinking about streamlining operations. I help firms your size figure out what they actually need. Quick question for you.",
      discoveryQuestions: [
        "What prompted you to start researching practice management tools right now? Was there a specific pain point?",
        "Without a dedicated PM tool, how is your team of 18 tracking deadlines and client work status?",
      ],
      objectionHandler: "If 'not ready yet': Totally fair. Most firms research for 2-3 months. Can I send you a case study of a firm that made the switch at exactly your size?",
      suggestedCTA: "Offer a 15-minute 'practice management assessment' — map out what they'd need.",
    },
  },
  {
    id: 'elevation',
    company: 'Elevation CPA Group',
    size: '35 employees',
    location: 'Austin, TX',
    industry: 'CPA & Advisory Services',
    revenue: '$4.6M ARR',
    currentTools: 'Canopy (basic plan)',
    founded: '2013',
    specialties: 'Tax advisory, startup accounting, CFO services',
    website: 'elevationcpa.com',
    aiScore: 85,
    fitScore: 86,
    intentScore: 84,
    timingScore: 82,
    dealValue: '$10,500/yr',
    seats: 35,
    whyPrioritized: 'Downloaded ROI calculator + viewed demo page in same session. Inbound signal pattern matches firms ready to evaluate. Canopy basic plan likely limiting as they scale.',
    contacts: [
      { name: 'Karen Ostrowski', title: 'Managing Partner', email: 'karen@elevationcpa.com', phone: '(512) 555-0678', isPrimary: true },
      { name: 'Derek Huang', title: 'Director of Client Services', email: 'derek@elevationcpa.com', phone: '(512) 555-0692' },
    ],
    signals: [
      { type: 'Content Download', detail: 'Downloaded ROI Calculator — entered firm size (35) and current tool (Canopy)', time: '1 day ago', strength: 'hot' },
      { type: 'Website Visit', detail: 'Viewed demo booking page but didn\'t schedule', time: '1 day ago', strength: 'hot' },
      { type: 'Email Engagement', detail: 'Opened 3 emails in nurture sequence this week', time: '2 days ago', strength: 'warm' },
    ],
    callScript: {
      opening: "Hi Karen, this is Sarah from Financial Cents. I noticed you ran our ROI calculator for a 35-person firm — the results for firms switching from Canopy are usually pretty compelling. Do you have a quick minute?",
      discoveryQuestions: [
        "You looked at the ROI calculator and the demo page — what's driving the evaluation right now?",
        "What's been the biggest limitation with Canopy as you've grown to 35 people?",
      ],
      objectionHandler: "If 'happy with Canopy': Many firms outgrow Canopy's basic plan around 30-35 people. The workflow depth gap usually shows up in reporting and capacity planning.",
      suggestedCTA: "Book the demo she almost scheduled — remove the friction.",
    },
  },
  {
    id: 'pacific',
    company: 'Pacific Northwest Bookkeeping',
    size: '22 employees',
    location: 'Portland, OR',
    industry: 'Bookkeeping Services',
    revenue: '$2.8M ARR',
    currentTools: 'Jetpack Workflow',
    founded: '2016',
    specialties: 'Cloud bookkeeping, payroll, monthly close services',
    website: 'pnwbookkeeping.com',
    aiScore: 76,
    fitScore: 80,
    intentScore: 74,
    timingScore: 77,
    dealValue: '$6,600/yr',
    seats: 22,
    whyPrioritized: 'Attended webinar on scaling and asked 2 questions in Q&A — active engagement signals genuine interest. Jetpack Workflow users often look for more robust solutions as they approach 25+ employees.',
    contacts: [
      { name: 'Robert Cheng', title: 'Owner / Principal', email: 'robert@pnwbookkeeping.com', phone: '(503) 555-0891', isPrimary: true },
      { name: 'Amy Torres', title: 'Team Lead', email: 'amy@pnwbookkeeping.com', phone: '(503) 555-0904' },
    ],
    signals: [
      { type: 'Webinar', detail: 'Attended "Scaling Your Bookkeeping Firm" webinar — asked 2 questions in Q&A', time: '2 days ago', strength: 'warm' },
      { type: 'Website Visit', detail: 'Viewed comparison page: Financial Cents vs Jetpack Workflow', time: '3 days ago', strength: 'warm' },
    ],
    callScript: {
      opening: "Hi Robert, this is Sarah from Financial Cents. You attended our scaling webinar and asked some great questions about team capacity planning — I wanted to follow up on that. Do you have a minute?",
      discoveryQuestions: [
        "You asked about capacity planning in the webinar — is that the biggest challenge as you scale?",
        "How is Jetpack Workflow handling things at 22 people? That's usually where firms start to feel the limits.",
      ],
      objectionHandler: "If 'Jetpack works fine': Many firms use Jetpack up to about 25 people. The gap usually shows up in capacity planning and client communication automation.",
      suggestedCTA: "Offer a side-by-side comparison of Jetpack vs Financial Cents for a 22-person firm.",
    },
  },
  {
    id: 'clearpath',
    company: 'Clearpath Financial Services',
    size: '40 employees',
    location: 'Phoenix, AZ',
    industry: 'Financial Services & Accounting',
    revenue: '$5.2M ARR',
    currentTools: 'Monday.com (generic PM)',
    founded: '2012',
    specialties: 'Wealth management accounting, tax planning, business advisory',
    website: 'clearpathfs.com',
    aiScore: 74,
    fitScore: 84,
    intentScore: 72,
    timingScore: 70,
    dealValue: '$12,000/yr',
    seats: 40,
    whyPrioritized: 'Clicked 4 emails in nurture sequence this week — engagement rate spiking. Using Monday.com (generic tool) at 40 employees means they lack accounting-specific workflows. Warming up for outreach.',
    contacts: [
      { name: 'Anita Desai', title: 'VP of Operations', email: 'anita@clearpathfs.com', phone: '(602) 555-0445', isPrimary: true },
      { name: 'Mark Sullivan', title: 'Managing Director', email: 'mark@clearpathfs.com', phone: '(602) 555-0461' },
    ],
    signals: [
      { type: 'Email Engagement', detail: 'Clicked 4 emails in nurture sequence this week — highest engagement in 90 days', time: '1 day ago', strength: 'warm' },
      { type: 'Website Visit', detail: 'Viewed "For Mid-Size Firms" page and pricing', time: '3 days ago', strength: 'warm' },
    ],
    callScript: {
      opening: "Hi Anita, this is Sarah from Financial Cents. I noticed your team has been engaging with our content about practice management for mid-size firms — we work with a lot of 40-person firms that outgrew generic tools like Monday.com. Quick question for you.",
      discoveryQuestions: [
        "What's working and what's not with Monday.com for managing accounting workflows?",
        "At 40 people, how are you handling accounting-specific needs like deadline tracking and client request automation?",
      ],
      objectionHandler: "If 'Monday.com works': It's a great tool — but firms your size usually find that accounting-specific workflows save 5-8 hours/week over a generic PM tool.",
      suggestedCTA: "Show a side-by-side: Monday.com vs purpose-built accounting PM tool for a 40-person firm.",
    },
  },
  {
    id: 'meridian',
    company: 'Meridian Accounting Group',
    size: '55 employees',
    location: 'Boston, MA',
    industry: 'Accounting & Consulting',
    revenue: '$7.8M ARR',
    currentTools: 'Unknown — new ICP match',
    founded: '2009',
    specialties: 'Audit, tax, consulting, business valuation',
    website: 'meridianaccounting.com',
    aiScore: 70,
    fitScore: 90,
    intentScore: 0,
    timingScore: 60,
    dealValue: '$16,500/yr',
    seats: 55,
    whyPrioritized: 'New company matched ICP perfectly — 55 employees, accounting vertical, Boston market. No intent signals yet but high fit score. Research and plan outreach for tomorrow.',
    contacts: [
      { name: 'TBD', title: 'Research needed', email: '', phone: '' },
    ],
    signals: [
      { type: 'ICP Match', detail: 'New company matched Ideal Customer Profile — 55 employees, accounting vertical', time: 'Today', strength: 'warm' },
    ],
    callScript: null,
  },
  {
    id: 'mountainview',
    company: 'Mountain View Tax',
    size: '15 employees',
    location: 'Salt Lake City, UT',
    industry: 'Tax Preparation Services',
    revenue: '$1.6M ARR',
    currentTools: 'Financial Cents (free trial — expired)',
    founded: '2019',
    specialties: 'Individual & small business tax, bookkeeping',
    website: 'mountainviewtax.com',
    aiScore: 82,
    fitScore: 79,
    intentScore: 88,
    timingScore: 90,
    dealValue: '$4,500/yr',
    seats: 15,
    whyPrioritized: 'Free trial expired yesterday — they experienced the product. Follow up while the experience is fresh. Trial usage data shows 3 active users, 12 workflows created. High conversion potential.',
    contacts: [
      { name: 'Steve Gallagher', title: 'Owner', email: 'steve@mountainviewtax.com', phone: '(801) 555-0334', isPrimary: true },
    ],
    signals: [
      { type: 'Trial Expiry', detail: 'Free trial expired yesterday — 3 active users, 12 workflows created during trial', time: 'Yesterday', strength: 'hot' },
      { type: 'Website Visit', detail: 'Visited pricing page after trial expiry', time: 'Yesterday', strength: 'hot' },
    ],
    callScript: {
      opening: "Hi Steve, this is Sarah from Financial Cents. Your free trial just wrapped up — I saw your team created 12 workflows during the trial which is great usage. I wanted to check in on your experience. Do you have a quick minute?",
      discoveryQuestions: [
        "How did the trial go? What did your team think of the workflow automation?",
        "Were there any features you wished you had more time to explore?",
      ],
      objectionHandler: "If 'need more time': Totally understand. I can extend your trial for another week so you can fully evaluate. No pressure.",
      suggestedCTA: "Offer trial extension or walk through pricing for a 15-person firm.",
    },
  },
];

export const dailyActions = [
  {
    id: 1,
    type: 'CALL',
    priority: 'urgent',
    contactName: 'David Whitfield',
    contactTitle: 'Managing Partner',
    contactPhone: '(404) 555-0142',
    contactEmail: 'd.whitfield@whitfieldcpas.com',
    accountId: 'whitfield',
    company: 'Whitfield & Associates CPAs',
    companySize: '45 employees',
    companyLocation: 'Atlanta, GA',
    action: 'Call David Whitfield — Whitfield & Associates CPAs',
    reason: 'Pricing page 3x this week + Practice Manager job posting. Ready to buy.',
    timeSlot: '9:00 AM',
    duration: '8 min',
    callBrief: [
      'Visited pricing 3x this week, compared annual vs monthly',
      'Posted Practice Manager role — needs PM software experience',
      'Opened comparison email + clicked CTA twice',
      'At 45 employees still on spreadsheets — critical pain point',
    ],
    openingLine: "Hi David, this is Sarah with Financial Cents. I noticed you just posted for a Practice Manager — sounds like you're scaling operations. I work with a lot of 40-50 person firms making that exact transition. Do you have 30 seconds?",
    discoveryQuestions: [
      "What's the biggest pain point driving the Practice Manager hire?",
      "How many hours per week does your team spend on manual status updates and deadline tracking?",
    ],
    objectionHandler: "If evaluating options: 'Most firms your size look at 2-3 tools. We're purpose-built for accounting firms. Happy to do a quick side-by-side.'",
    suggestedCTA: 'Book a 15-minute demo tailored to firms transitioning from spreadsheets.',
  },
  {
    id: 2,
    type: 'EMAIL',
    priority: 'urgent',
    contactName: 'Rachel Morrison',
    contactTitle: 'CEO / Founder',
    contactEmail: 'rachel@summitledger.com',
    accountId: 'summit',
    company: 'Summit Ledger Group',
    companySize: '28 employees',
    companyLocation: 'Denver, CO',
    action: 'Email Rachel Morrison — Summit Ledger Group',
    reason: 'Pre-call warm-up: Reference their TaxDome migration research.',
    timeSlot: '9:10 AM',
    duration: '3 min',
    emailSubject: 'Switching from TaxDome? Here\'s what 200+ firms learned',
    emailBody: `Hi Rachel,

I noticed your team has been researching TaxDome alternatives — you're not alone. We've helped over 200 bookkeeping firms make that exact transition in the last year.

The most common feedback? Financial Cents gives them the workflow depth TaxDome lacks — real capacity planning, automated client requests, and reporting that shows firm-wide performance.

Most migrations take under 10 days with zero data loss.

Would a quick migration assessment be helpful? I can show you exactly what the transition looks like for a 28-person firm like Summit Ledger.

Best,
Sarah`,
  },
  {
    id: 3,
    type: 'CALL',
    priority: 'urgent',
    contactName: 'Patricia Brennan',
    contactTitle: 'COO',
    contactPhone: '(312) 555-0456',
    contactEmail: 'p.brennan@brookhaventax.com',
    accountId: 'brookhaven',
    company: 'Brookhaven Tax & Advisory',
    companySize: '62 employees, 2 offices',
    companyLocation: 'Chicago, IL',
    action: 'Call Patricia Brennan — Brookhaven Tax & Advisory',
    reason: 'Replied asking for Karbon comparison. Demo-ready lead.',
    timeSlot: '9:15 AM',
    duration: '10 min',
    callBrief: [
      'Replied to sequence asking for Karbon comparison — warmest lead',
      'Attended scaling webinar, stayed for full Q&A',
      'IT Director (Tom Nakamura) connected with sales rep on LinkedIn',
      '62 employees across 2 offices — multi-office visibility pain',
    ],
    openingLine: "Hi Patricia, this is Sarah with Financial Cents. Thank you for your reply asking about the Karbon comparison — I put together a side-by-side specifically for 60+ person firms. Want me to walk you through the highlights?",
    discoveryQuestions: [
      "What specifically about Karbon is prompting you to look at alternatives?",
      "How are you handling workflow visibility between your two offices today?",
    ],
    objectionHandler: "If need more stakeholders: 'I saw Tom from IT already connected with us. Happy to set up a session for the full evaluation team.'",
    suggestedCTA: 'Schedule Karbon comparison demo — include Patricia and Tom on the invite.',
  },
  {
    id: 4,
    type: 'LINKEDIN',
    priority: 'high',
    contactName: 'Tom Nakamura',
    contactTitle: 'IT Director',
    contactEmail: 't.nakamura@brookhaventax.com',
    accountId: 'brookhaven',
    company: 'Brookhaven Tax & Advisory',
    action: 'LinkedIn — Tom Nakamura, Brookhaven Tax & Advisory',
    reason: 'Accept connection + send intro message. IT Director evaluating tools.',
    timeSlot: '9:30 AM',
    duration: '2 min',
    linkedinMessage: `Hi Tom — thanks for connecting! I saw Brookhaven Tax is evaluating practice management tools. As IT Director, you're probably thinking about integration requirements, data migration, and security.

Happy to share our technical spec sheet and API documentation. We integrate natively with QuickBooks, Xero, and all major tax software. Let me know if that would be helpful.`,
  },
  {
    id: 5,
    type: 'CALL',
    priority: 'high',
    contactName: 'Rachel Morrison',
    contactTitle: 'CEO / Founder',
    contactPhone: '(720) 555-0318',
    contactEmail: 'rachel@summitledger.com',
    accountId: 'summit',
    company: 'Summit Ledger Group',
    companySize: '28 employees',
    companyLocation: 'Denver, CO',
    action: 'Call Rachel Morrison — Summit Ledger Group',
    reason: 'CEO researching TaxDome alternatives. Migration guide viewed yesterday.',
    timeSlot: '9:35 AM',
    duration: '8 min',
    callBrief: [
      'CEO personally engaging with competitor-switching content',
      'Visited TaxDome migration guide — spent 4 minutes reading',
      'Viewed "Switch from TaxDome" comparison page',
      'TaxDome recent pricing changes pushing firms to evaluate',
    ],
    openingLine: "Hi Rachel, this is Sarah from Financial Cents. I noticed your team has been researching practice management alternatives — a lot of bookkeeping firms we work with made a similar move from TaxDome recently. Quick question for you.",
    discoveryQuestions: [
      "What initially drew you to TaxDome, and what's changed?",
      "With 28 people, how is TaxDome handling workflow management and capacity planning?",
    ],
    objectionHandler: "If just renewed TaxDome: 'Most firms that switch planned it a quarter in advance. Happy to do a comparison now so you're ready at renewal.'",
    suggestedCTA: 'Offer a free migration assessment for a 28-person firm.',
  },
  {
    id: 6,
    type: 'EMAIL',
    priority: 'standard',
    contactName: 'Mike Donovan',
    contactTitle: 'Founding Partner',
    contactEmail: 'mike@coastalaccounting.com',
    accountId: 'coastal',
    company: 'Coastal Accounting Partners',
    companySize: '18 employees',
    companyLocation: 'San Diego, CA',
    action: 'Email Mike Donovan — Coastal Accounting Partners',
    reason: "Send buyer's guide follow-up with small firm case study.",
    timeSlot: '9:45 AM',
    duration: '3 min',
    emailSubject: 'Quick case study: How an 18-person firm eliminated spreadsheet chaos',
    emailBody: `Hi Mike,

I saw you downloaded our Practice Management Buyer's Guide — great resource for firms in research mode.

I wanted to share a quick case study that might hit home: Cedar Creek Accounting (19 employees, very similar to Coastal) was running on email and Google Sheets just like your team. After switching to Financial Cents:

- Saved 12 hours/week on manual status tracking
- Reduced missed deadlines by 94%
- Onboarded new team members 3x faster with workflow templates

The best part? They were fully up and running in 5 days — no complex implementation.

Would it be worth 15 minutes to see if this could work for Coastal Accounting?

Best,
Sarah`,
  },
  {
    id: 7,
    type: 'CALL',
    priority: 'high',
    contactName: 'Karen Ostrowski',
    contactTitle: 'Managing Partner',
    contactPhone: '(512) 555-0678',
    contactEmail: 'karen@elevationcpa.com',
    accountId: 'elevation',
    company: 'Elevation CPA Group',
    companySize: '35 employees',
    companyLocation: 'Austin, TX',
    action: 'Call Karen Ostrowski — Elevation CPA Group',
    reason: 'Downloaded ROI calculator + viewed demo page. Inbound signal.',
    timeSlot: '9:50 AM',
    duration: '8 min',
    callBrief: [
      'Downloaded ROI calculator — entered 35 employees + Canopy as current tool',
      'Viewed demo booking page but didn\'t schedule',
      'Opened 3 emails in nurture sequence this week',
      'On Canopy basic plan — likely hitting limitations at 35 people',
    ],
    openingLine: "Hi Karen, this is Sarah from Financial Cents. I noticed you ran our ROI calculator for a 35-person firm — the results for firms switching from Canopy are usually pretty compelling. Do you have a quick minute?",
    discoveryQuestions: [
      "You looked at the ROI calculator and the demo page — what's driving the evaluation?",
      "What's been the biggest limitation with Canopy as you've grown to 35 people?",
    ],
    objectionHandler: "If happy with Canopy: 'Many firms outgrow Canopy's basic plan around 30-35 people. The gap usually shows up in reporting and capacity planning.'",
    suggestedCTA: 'Book the demo she almost scheduled — remove the friction.',
  },
  {
    id: 8,
    type: 'FOLLOW-UP',
    priority: 'standard',
    contactName: 'James Park',
    contactTitle: 'Operations Lead',
    contactEmail: 'james@summitledger.com',
    accountId: 'summit',
    company: 'Summit Ledger Group',
    action: 'Follow up — James Park, Summit Ledger Group',
    reason: 'Re-send migration assessment offer. Opened last email but didn\'t reply.',
    timeSlot: '10:00 AM',
    duration: '2 min',
    emailSubject: 'Re: TaxDome migration assessment for Summit Ledger',
    emailBody: `Hi James,

Just wanted to bump this to the top of your inbox — I know operations leads are swamped this time of year.

The migration assessment I mentioned is completely free and takes about 20 minutes. We'd map out:
- Your current TaxDome workflows and how they transfer
- Timeline and data migration plan
- Training requirements for your 28-person team

Rachel has also been looking into this on your team's behalf. Would it make sense to loop her in for a quick call?

Best,
Sarah`,
  },
  {
    id: 9,
    type: 'CALL',
    priority: 'standard',
    contactName: 'Robert Cheng',
    contactTitle: 'Owner / Principal',
    contactPhone: '(503) 555-0891',
    contactEmail: 'robert@pnwbookkeeping.com',
    accountId: 'pacific',
    company: 'Pacific Northwest Bookkeeping',
    companySize: '22 employees',
    companyLocation: 'Portland, OR',
    action: 'Call Robert Cheng — Pacific Northwest Bookkeeping',
    reason: 'Attended webinar on scaling, asked 2 questions in Q&A.',
    timeSlot: '10:05 AM',
    duration: '8 min',
    callBrief: [
      'Attended "Scaling Your Bookkeeping Firm" webinar',
      'Asked 2 questions in Q&A about capacity planning',
      'Viewed Financial Cents vs Jetpack Workflow comparison page',
      'Currently on Jetpack Workflow — likely hitting limits at 22 employees',
    ],
    openingLine: "Hi Robert, this is Sarah from Financial Cents. You attended our scaling webinar and asked some great questions about capacity planning — I wanted to follow up. Do you have a minute?",
    discoveryQuestions: [
      "You asked about capacity planning in the webinar — is that the biggest challenge as you scale?",
      "How is Jetpack Workflow handling things at 22 people?",
    ],
    objectionHandler: "If Jetpack works fine: 'Many firms use Jetpack up to about 25 people. The gap usually shows up in capacity planning and client communication automation.'",
    suggestedCTA: 'Offer a side-by-side: Jetpack vs Financial Cents for a 22-person firm.',
  },
  {
    id: 10,
    type: 'EMAIL',
    priority: 'high',
    contactName: 'Lisa Ferraro',
    contactTitle: 'Managing Partner',
    contactEmail: 'l.ferraro@brookhaventax.com',
    accountId: 'brookhaven',
    company: 'Brookhaven Tax & Advisory',
    action: 'Email Lisa Ferraro — Brookhaven Tax & Advisory',
    reason: 'Send Karbon comparison deck to Managing Partner. Multi-thread the deal.',
    timeSlot: '10:15 AM',
    duration: '3 min',
    emailSubject: 'Karbon vs Financial Cents — comparison for 60+ person firms',
    emailBody: `Hi Lisa,

Your colleague Patricia Brennan asked about our Karbon comparison, and I wanted to make sure you had it too — I know these decisions involve multiple perspectives at the leadership level.

For a 62-person firm across 2 offices like Brookhaven, the key differences are:

- Cross-office workflow visibility (real-time, no manual updates)
- Capacity planning across teams and locations
- 30% faster engagement completion (avg. for firms switching from Karbon)
- Partner-level reporting dashboards vs task-level views

I put together a custom comparison based on Brookhaven's size. Would 15 minutes be worth it to walk through the highlights?

Best,
Sarah`,
  },
  {
    id: 11,
    type: 'LINKEDIN',
    priority: 'standard',
    contactName: 'David Whitfield',
    contactTitle: 'Managing Partner',
    accountId: 'whitfield',
    company: 'Whitfield & Associates CPAs',
    action: 'LinkedIn — David Whitfield, Whitfield & Associates',
    reason: 'Share relevant article on practice management scaling. Stay top of mind.',
    timeSlot: '10:20 AM',
    duration: '2 min',
    linkedinMessage: `Great article on scaling firm operations, David — thought of you given Whitfield's growth trajectory. The section on moving from spreadsheets to dedicated PM tools at the 40-50 employee mark is spot-on.

[Share: "5 Signs Your Accounting Firm Has Outgrown Spreadsheets"]`,
  },
  {
    id: 12,
    type: 'CALL',
    priority: 'standard',
    contactName: 'Anita Desai',
    contactTitle: 'VP of Operations',
    contactPhone: '(602) 555-0445',
    contactEmail: 'anita@clearpathfs.com',
    accountId: 'clearpath',
    company: 'Clearpath Financial Services',
    companySize: '40 employees',
    companyLocation: 'Phoenix, AZ',
    action: 'Call Anita Desai — Clearpath Financial Services',
    reason: 'Clicked 4 emails in nurture sequence this week. Warming up.',
    timeSlot: '10:25 AM',
    duration: '8 min',
    callBrief: [
      'Clicked 4 emails in nurture sequence — highest engagement in 90 days',
      'Viewed "For Mid-Size Firms" page and pricing',
      'Currently using Monday.com — generic PM tool, not accounting-specific',
      '40 employees — at the size where generic tools create friction',
    ],
    openingLine: "Hi Anita, this is Sarah from Financial Cents. I noticed your team has been engaging with our content about practice management for mid-size firms — we work with a lot of 40-person firms that outgrew generic tools like Monday.com. Quick question for you.",
    discoveryQuestions: [
      "What's working and what's not with Monday.com for managing accounting workflows?",
      "At 40 people, how are you handling accounting-specific needs like deadline tracking?",
    ],
    objectionHandler: "If Monday.com works: 'It's a great tool — but firms your size usually find that accounting-specific workflows save 5-8 hours/week.'",
    suggestedCTA: 'Show a side-by-side: Monday.com vs purpose-built PM tool for 40-person firm.',
  },
  {
    id: 13,
    type: 'RESEARCH',
    priority: 'standard',
    contactName: '',
    accountId: 'meridian',
    company: 'Meridian Accounting Group',
    companySize: '55 employees',
    companyLocation: 'Boston, MA',
    action: 'Research — Meridian Accounting Group',
    reason: 'New company matched ICP. Research before outreach tomorrow.',
    timeSlot: '10:35 AM',
    duration: '5 min',
    researchTasks: [
      'Find key decision makers on LinkedIn (COO, Managing Partner, Ops Director)',
      'Check current tech stack via job postings and BuiltWith',
      'Review recent news, blog posts, or LinkedIn activity',
      'Identify potential pain points based on firm size and specialties',
      'Draft initial outreach angle for tomorrow\'s sequence',
    ],
  },
  {
    id: 14,
    type: 'CALL',
    priority: 'high',
    contactName: 'Steve Gallagher',
    contactTitle: 'Owner',
    contactPhone: '(801) 555-0334',
    contactEmail: 'steve@mountainviewtax.com',
    accountId: 'mountainview',
    company: 'Mountain View Tax',
    companySize: '15 employees',
    companyLocation: 'Salt Lake City, UT',
    action: 'Call Steve Gallagher — Mountain View Tax',
    reason: 'Free trial expired yesterday. Follow up on experience.',
    timeSlot: '10:40 AM',
    duration: '8 min',
    callBrief: [
      'Free trial expired yesterday — 3 active users during trial',
      '12 workflows created during trial — strong product engagement',
      'Visited pricing page after trial expiry',
      '15 employees — perfect fit for small firm pricing tier',
    ],
    openingLine: "Hi Steve, this is Sarah from Financial Cents. Your free trial just wrapped up — I saw your team created 12 workflows during the trial which is great usage. I wanted to check in on your experience. Do you have a quick minute?",
    discoveryQuestions: [
      "How did the trial go? What did your team think of the workflow automation?",
      "Were there any features you wished you had more time to explore?",
    ],
    objectionHandler: "If need more time: 'Totally understand. I can extend your trial for another week so you can fully evaluate.'",
    suggestedCTA: 'Offer trial extension or walk through pricing for a 15-person firm.',
  },
  {
    id: 15,
    type: 'EMAIL',
    priority: 'high',
    contactName: 'Karen Ostrowski',
    contactTitle: 'Managing Partner',
    contactEmail: 'karen@elevationcpa.com',
    accountId: 'elevation',
    company: 'Elevation CPA Group',
    action: 'Email Karen Ostrowski — Elevation CPA Group',
    reason: 'Post-call follow-up with custom ROI projection. Strike while hot.',
    timeSlot: '10:50 AM',
    duration: '3 min',
    emailSubject: 'Your custom ROI projection — Elevation CPA Group',
    emailBody: `Hi Karen,

Great speaking with you! As promised, here's the custom ROI projection for Elevation CPA Group based on your 35-person team:

Projected annual savings with Financial Cents:
- Workflow automation: ~8 hrs/week saved = $31,200/yr in recovered capacity
- Reduced missed deadlines: 94% improvement (industry avg.)
- Faster onboarding: New hires productive in days, not weeks
- Your investment: $10,500/yr (35 seats at $25/mo)

Net ROI: 3x your investment in year one.

I have a 15-minute demo slot open Thursday at 2 PM — perfect for a quick walkthrough with your team. Want me to send a calendar invite?

Best,
Sarah`,
  },
  {
    id: 16,
    type: 'CALL',
    priority: 'standard',
    contactName: 'Jen Castellano',
    contactTitle: 'Office Manager',
    contactPhone: '(619) 555-0234',
    contactEmail: 'jen@coastalaccounting.com',
    accountId: 'coastal',
    company: 'Coastal Accounting Partners',
    companySize: '18 employees',
    companyLocation: 'San Diego, CA',
    action: 'Call Jen Castellano — Coastal Accounting Partners',
    reason: 'Office Manager — connect on operational pain. Warmer entry than founder.',
    timeSlot: '10:55 AM',
    duration: '8 min',
    callBrief: [
      'Office Manager — likely the one feeling spreadsheet pain daily',
      'Mike (Founder) downloaded buyer\'s guide — firm is in research mode',
      'No PM tool at 18 people — managing with email + Google Sheets',
      'Warmer entry point than going directly to the founder again',
    ],
    openingLine: "Hi Jen, this is Sarah from Financial Cents. I work with a lot of office managers at 15-20 person accounting firms, and I know you're probably the one keeping everything running. I had a quick question about how you track workflow and deadlines at Coastal.",
    discoveryQuestions: [
      "How are you currently tracking client work status and team deadlines?",
      "What's the most frustrating part of managing workflow with email and spreadsheets?",
    ],
    objectionHandler: "If 'talk to Mike': 'Totally understand — Mike actually downloaded our buyer's guide recently. Would it help if I sent you both a quick comparison so you can evaluate together?'",
    suggestedCTA: 'Get Jen bought in on the operational benefits, then loop in Mike for a joint demo.',
  },
  {
    id: 17,
    type: 'LINKEDIN',
    priority: 'standard',
    contactName: 'Patricia Brennan',
    contactTitle: 'COO',
    accountId: 'brookhaven',
    company: 'Brookhaven Tax & Advisory',
    action: 'LinkedIn — Patricia Brennan, Brookhaven Tax & Advisory',
    reason: 'Engage with her recent LinkedIn post about firm growth.',
    timeSlot: '11:05 AM',
    duration: '2 min',
    linkedinMessage: `Great insights on scaling firm operations, Patricia! The point about cross-office communication is especially relevant — we see that challenge a lot with firms growing past 50 employees. Would love to hear more about how Brookhaven is tackling it.

[Like + thoughtful comment on her recent post about firm growth challenges]`,
  },
  {
    id: 18,
    type: 'CREATE DEAL',
    priority: 'urgent',
    contactName: '',
    accountId: 'whitfield',
    company: 'Whitfield & Associates CPAs',
    action: 'Create Deal — Whitfield & Associates CPAs',
    reason: 'Create deal: $14,400/yr, 45 seats. Move to "Demo Scheduled" stage.',
    timeSlot: '11:10 AM',
    duration: '2 min',
    dealDetails: {
      dealName: 'Whitfield & Associates — Practice Management',
      amount: '$14,400/yr',
      seats: 45,
      stage: 'Demo Scheduled',
      closeDate: 'April 15, 2026',
      primaryContact: 'David Whitfield, Managing Partner',
      notes: 'Hot prospect — pricing page 3x, PM job posting, email engagement. Multi-threaded with Practice Manager and Dir of Ops.',
    },
  },
];

export const signalFeed = [
  { id: 1, accountId: 'whitfield', account: 'Whitfield & Associates CPAs', action: 'Visited pricing page — 3rd time this week, compared annual vs monthly', time: '2 hours ago', type: 'website', strength: 'hot' },
  { id: 2, accountId: 'summit', account: 'Summit Ledger Group', action: 'Viewed TaxDome migration guide — spent 4 minutes reading', time: '4 hours ago', type: 'website', strength: 'hot' },
  { id: 3, accountId: 'whitfield', account: 'Whitfield & Associates CPAs', action: 'Opened comparison email "Financial Cents vs Spreadsheets" — clicked CTA', time: '5 hours ago', type: 'email', strength: 'hot' },
  { id: 4, accountId: 'brookhaven', account: 'Brookhaven Tax & Advisory', action: 'Replied to sequence: "Can we see the Karbon comparison?"', time: '6 hours ago', type: 'email', strength: 'hot' },
  { id: 5, accountId: 'summit', account: 'Summit Ledger Group', action: 'CEO liked Financial Cents post about switching PM tools', time: '8 hours ago', type: 'linkedin', strength: 'hot' },
  { id: 6, accountId: 'mountainview', account: 'Mountain View Tax', action: 'Free trial expired — 3 active users, 12 workflows created', time: 'Yesterday', type: 'website', strength: 'hot' },
  { id: 7, accountId: 'whitfield', account: 'Whitfield & Associates CPAs', action: 'Posted "Practice Manager" role on LinkedIn — requires PM software', time: '1 day ago', type: 'job', strength: 'hot' },
  { id: 8, accountId: 'elevation', account: 'Elevation CPA Group', action: 'Downloaded ROI Calculator — entered 35 employees, Canopy', time: '1 day ago', type: 'website', strength: 'hot' },
  { id: 9, accountId: 'elevation', account: 'Elevation CPA Group', action: 'Viewed demo booking page but didn\'t schedule', time: '1 day ago', type: 'website', strength: 'hot' },
  { id: 10, accountId: 'coastal', account: 'Coastal Accounting Partners', action: 'Downloaded "Practice Management Buyer\'s Guide" whitepaper', time: '1 day ago', type: 'website', strength: 'warm' },
  { id: 11, accountId: 'mountainview', account: 'Mountain View Tax', action: 'Visited pricing page after trial expiry', time: 'Yesterday', type: 'website', strength: 'hot' },
  { id: 12, accountId: 'clearpath', account: 'Clearpath Financial Services', action: 'Clicked 4 emails in nurture sequence — highest engagement in 90 days', time: '1 day ago', type: 'email', strength: 'warm' },
  { id: 13, accountId: 'summit', account: 'Summit Ledger Group', action: 'Viewed "Switch from TaxDome" comparison page', time: '1 day ago', type: 'website', strength: 'hot' },
  { id: 14, accountId: 'pacific', account: 'Pacific Northwest Bookkeeping', action: 'Attended webinar, asked 2 questions about capacity planning', time: '2 days ago', type: 'website', strength: 'warm' },
  { id: 15, accountId: 'summit', account: 'Summit Ledger Group', action: 'Opened drip email: "Why bookkeeping firms are leaving TaxDome"', time: '2 days ago', type: 'email', strength: 'warm' },
  { id: 16, accountId: 'whitfield', account: 'Whitfield & Associates CPAs', action: 'Viewed case study: "50-person firm eliminated spreadsheet chaos"', time: '2 days ago', type: 'website', strength: 'warm' },
  { id: 17, accountId: 'coastal', account: 'Coastal Accounting Partners', action: 'Read 3 blog posts on workflow automation in 2 days', time: '2 days ago', type: 'website', strength: 'warm' },
  { id: 18, accountId: 'elevation', account: 'Elevation CPA Group', action: 'Opened 3 emails in nurture sequence this week', time: '2 days ago', type: 'email', strength: 'warm' },
  { id: 19, accountId: 'brookhaven', account: 'Brookhaven Tax & Advisory', action: 'Attended "Scaling Beyond 50 Employees" webinar — full Q&A', time: '3 days ago', type: 'website', strength: 'warm' },
  { id: 20, accountId: 'whitfield', account: 'Whitfield & Associates CPAs', action: 'David Whitfield liked Financial Cents LinkedIn post', time: '3 days ago', type: 'linkedin', strength: 'warm' },
  { id: 21, accountId: 'coastal', account: 'Coastal Accounting Partners', action: 'Visited "For Small Firms" landing page and features overview', time: '3 days ago', type: 'website', strength: 'warm' },
  { id: 22, accountId: 'clearpath', account: 'Clearpath Financial Services', action: 'Viewed "For Mid-Size Firms" page and pricing', time: '3 days ago', type: 'website', strength: 'warm' },
  { id: 23, accountId: 'pacific', account: 'Pacific Northwest Bookkeeping', action: 'Viewed comparison: Financial Cents vs Jetpack Workflow', time: '3 days ago', type: 'website', strength: 'warm' },
  { id: 24, accountId: 'brookhaven', account: 'Brookhaven Tax & Advisory', action: 'Viewed features page — 6 min on workflow automation', time: '4 days ago', type: 'website', strength: 'warm' },
  { id: 25, accountId: 'brookhaven', account: 'Brookhaven Tax & Advisory', action: 'IT Director connected with Financial Cents sales rep', time: '5 days ago', type: 'linkedin', strength: 'warm' },
  { id: 26, accountId: 'meridian', account: 'Meridian Accounting Group', action: 'New company matched ICP — 55 employees, accounting vertical', time: 'Today', type: 'website', strength: 'warm' },
];

export const performanceData = {
  actionsToday: 0,
  actionsTotal: 18,
  callsToday: 0,
  callsTotal: 8,
  emailsToday: 0,
  emailsTotal: 5,
  linkedinToday: 0,
  linkedinTotal: 3,
  followUpsToday: 0,
  followUpsTotal: 2,
  pipelineInfluenced: 0,
  pipelineTarget: 86400,
  weeklyCompletion: [
    { day: 'Mon', completed: 16, total: 18, pipeline: 42000 },
    { day: 'Tue', completed: 17, total: 19, pipeline: 38000 },
    { day: 'Wed', completed: 14, total: 16, pipeline: 51000 },
    { day: 'Thu', completed: 18, total: 20, pipeline: 44000 },
    { day: 'Fri', completed: 0, total: 18, pipeline: 0 },
  ],
  conversionRates: {
    signalToCall: '78%',
    callToMeeting: '34%',
    meetingToDemo: '62%',
    demoToClose: '28%',
  },
  topPerformingSignals: [
    { signal: 'Email Reply', conversion: 67 },
    { signal: 'Pricing Page (3+ visits)', conversion: 52 },
    { signal: 'Trial Expiry', conversion: 48 },
    { signal: 'Competitor Research', conversion: 41 },
    { signal: 'ROI Calculator Download', conversion: 38 },
    { signal: 'Webinar Attendance', conversion: 31 },
    { signal: 'Content Download', conversion: 28 },
    { signal: 'Job Posting', conversion: 24 },
  ],
};
